Added LinearSearch,QuickSort,InsertionSort
rohan8594/DS-Algos pull request #6
Opened 2020-10-06 07:32 UTC by shubham2704

## Implemented the Algorithms under the issue #1 

## Algorithms added:
QuickSort
InsertionSort
LinearSearch

## Language:
python

2020-10-06 08:09 UTC, rohan8594 commented
@shubham2704 I'll review and merge this over the weekend. Can you pls in the meantime create a separate issue mentioning these algorithms and reference that issue on here. So that no one adds these again.

2020-10-06 08:29 UTC, shubham2704 commented
> @shubham2704 I'll review and merge this over the weekend. Can you pls in the meantime create a separate issue mentioning these algorithms and reference that issue on here. So that no one adds these again.

yeah sure i will do it

2020-10-11 00:16 UTC, rohan8594 requested changes

2020-10-11 00:16 UTC, rohan8594 commented on algorithms/Sorting/InsertionSort.py
> +       arr[j+1] = key
Please fix the indentation here. Python will throw an indentation error

2020-10-11 09:02 UTC, shubham2704 commented
@rohan8594 fixed the indentation .☑

2020-10-11 19:08 UTC, rohan8594 approved these changes

2020-10-11 19:09 UTC, rohan8594 commented
@all-contributors please add @shubham2704 for code

2020-10-11 19:09 UTC, merged